// Auto-generated from dragonsurvival-mcdoc-completion-zh-2.0.4
export const MCDOC_FIELD_INFO: Record<string, string> = {
  "species": "指定使用该龙魂图标的物种id",
  "stage": "指定使用该龙魂图标的物种阶段id",
  "model": "指定龙魂将使用的烘焙模型(https://zh.minecraft.wiki/w/烘焙模型)",
  "body": "指定该 默认组件表 将映射至的身体类型id 不填写默认所有身体类型都适用",
  "parts": "该物种此阶段将使用的默认皮肤组件",
  "base": "基础 - 使用`assets\\<命名空间>\\skin\\parts\\base\\`目录下JSON文件中key的值",
  "bottom": "底部 - 使用`assets\\<命名空间>\\skin\\parts\\bottom\\`目录下JSON文件中key的值",
  "eyes": "眼 - 使用`assets\\<命名空间>\\skin\\parts\\eyes\\`目录下JSON文件中key的值",
  "horns": "角 - 使用`assets\\<命名空间>\\skin\\parts\\horns\\`目录下JSON文件中key的值",
  "spikes": "背棘 - 使用`assets\\<命名空间>\\skin\\parts\\spikes\\`目录下JSON文件中key的值",
  "claws": "爪 - 使用`assets\\<命名空间>\\skin\\parts\\claws\\`目录下JSON文件中key的值",
  "teeth": "牙齿 - 使用`assets\\<命名空间>\\skin\\parts\\teeth\\`目录下JSON文件中key的值",
  "magic": "魔法 - 使用`assets\\<命名空间>\\skin\\parts\\magic\\`目录下JSON文件中key的值",
  "extra": "额外 - 使用`assets\\<命名空间>\\skin\\parts\\extra\\`目录下JSON文件中key的值",
  "extra1": "额外1 - 使用`assets\\<命名空间>\\skin\\parts\\extra\\`目录下JSON文件中key的值",
  "extra2": "额外2 - 使用`assets\\<命名空间>\\skin\\parts\\extra\\`目录下JSON文件中key的值",
  "extra3": "额外3 - 使用`assets\\<命名空间>\\skin\\parts\\extra\\`目录下JSON文件中key的值",
  "extra4": "额外4 - 使用`assets\\<命名空间>\\skin\\parts\\extra\\`目录下JSON文件中key的值",
  "extra5": "额外5 - 使用`assets\\<命名空间>\\skin\\parts\\extra\\`目录下JSON文件中key的值",
  "extra6": "额外6 - 使用`assets\\<命名空间>\\skin\\parts\\extra\\`目录下JSON文件中key的值",
  "extra7": "额外7 - 使用`assets\\<命名空间>\\skin\\parts\\extra\\`目录下JSON文件中key的值",
  "key": "组件标识符，应与JSON文件名一致",
  "localization": "使用文本组件定义皮肤组件本地化文本 - 若不填写将使用`skin_part.<命名空间>.<物种id>.<该JSON定义的key值>`作为本地化键, 例如`skin_part.dragonsurvival.sea_dragon.base_1`",
  "texture": "此皮肤组件将使用的贴图 此处的资源的注册方式与原版的`\"命名空间:资源路径\"`不同 - 若用图片`assets/dragonsurvival/textures/dragon/custom/cave_base_2.png` - 请这么写`\"dragonsurvival:textures/dragon/custom/cave_base_2.png\"`",
  "applicable_species": "可应用该组件的物种列表",
  "applicable_bodies": "可应用该组件的身体类型列表",
  "average_hue": "平均色相 - 这将在游戏中调整皮肤组件色相时作为默认值 - 可通过龙之生存mod中自带的`assets\\dragonsurvival\\colors.py`脚本批处理",
  "is_colorable": "可能有颜色的 (默认: true)",
  "include_in_randomizer": "该组件是否包含在随机选择器中 (默认: true)",
  "is_hue_randomizable": "色相是否允许被随机化 (默认: true)",
  "is_glowing": "是否默认发光 (默认: false)",
  "dragon_species": "检查玩家是否属于特定的物种",
  "stage_specific": "检查龙玩家的成长阶段和成长进度",
  "dragon_body": "检查玩家是否使用了给定的龙身体类型 例如 `dragonsurvival:center`",
  "ability_levels": "检查技能/能力等级",
  "is_growth_stopped": "检查龙的成长是否被手动停止",
  "marked_by_ender_dragon": "当末影龙死亡且玩家曾对其造成伤害时设置此标志 在末地维度与充能状态的原初锚方块交互时清除 (需满足末影龙存活且方块处于充能状态)",
  "flight_was_granted": "检查飞行能力是否被授予 若相关配置启用，原初锚也可将其设为'true'",
  "spin_was_granted": "检查旋转能力是否被授予 若相关配置启用，原初锚也可将其设为'true'",
  "is_flying": "用于检测龙是否正在飞行(仅检测龙生的飞行)",
  "ability": "需要查询的技能/能力",
  "level": "需要检查的等级",
  "dragon_stage": "检查玩家的成长进度(龙阶段) 例如 `dragonsurvival:adult`",
  "growth_percentage": "检查在当前阶段内的完成度(0-100%)",
  "growth": "检查成长值的原始数值",
  "check_for": "检查实体类型 - `living_entity` 活着的实体 - `enemy` 敌对生物(Enemy 接口实现类或Mob子类实体) - `tamed` 已被驯服的生物(TamableAnimal 且已被驯服) - `animal` 动物(Animal 的子类) - `item` 物品实体 - `experience_or` 经验球",
  "eye_in_fluid": "实体眼睛是否处于特定流体中(如水中、熔岩中)",
  "weather_predicate": "天气相关的判断条件(内部判断用的逻辑是and)",
  "sun_light_level": "检测天空光照等级",
  "has_duration_effect": "是否拥有特定的，由 `dragonsurvival:modifier` 实现的持续效果",
  "is_nearby_entity": "附近是否存在符合条件的实体",
  "player_hunger": "玩家饥饿值范围",
  "health_percentage": "实体健康值百分比范围",
  "has_uuid": "实体是否具有特定的UUID",
  "looking_at_block": "实体是否看向特定的方块",
  "is_raining": "正在下雨",
  "is_thundering": "处于雷暴天气",
  "is_snowing": "正在下雪",
  "is_raining_or_snowing": "正在下雨或下雪 - 性能优于单独检测雨天和雪天",
  "entity_types": "要检查的实体类型",
  "radius": "进行检测的范围半径",
  "item_from": "检查从什么物品进行转换",
  "item_to": "检查转换成的物品",
  "nearby_treasure_amount": "睡在指定片数以上的财宝堆中才能触发",
  "nutrition": "吃掉后给予的饥饿值(上限为20.0)",
  "saturation": "吃掉后恢复的饱和度",
  "can_always_eat": "当玩家的饥饿槽/饱和度满的时候，物品是否可以吃? (默认: false)",
  "eat_seconds": "吃这个物品所需的时间(以秒为单位) 默认为`1.6`",
  "effects": "吃掉后给予的药水效果",
  "using_converts_to": "与牛奶桶的工作方式类似",
  "items": "有效的资源位置（命名空间:路径） 命名空间和路径中允许使用正则表达式",
  "properties": "定义具体的食物效果",
  "retain_effects": "是否继承物品原本拥有的状态效果 (默认:：false)",
  "growth_icon": "成长阶段图标 - 会出现在龙背包的右上角、物种旗帜左上角等位置",
  "default_skin": "默认皮肤贴图 - 会出现在物种选择界面、选择测试资源包的时候作为皮肤",
  "hover_icon": "鼠标悬停时显示的替换图标资源路径 此处的资源的注册方式与原版的`\"命名空间:资源路径\"`不同 - 若用图片`assets/dragonsurvival/textures/gui/custom/stage/sea/adult_stage_hover.png` - 请这么写`\"dragonsurvival:textures/gui/custom/stage/sea/adult_stage_hover.png\"`",
  "icon": "普通图标资源路径 此处的资源的注册方式与原版的`\"命名空间:资源路径\"`不同 - 若用图片`assets/dragonsurvival/textures/gui/custom/stage/sea/adult_stage_main.png` - 请这么写`\"dragonsurvival:textures/gui/custom/stage/sea/adult_stage_main.png\"`",
  "skin": "皮肤纹理资源路径 此处的资源的注册方式与原版的`\"命名空间:资源路径\"`不同 - 若用图片`assets/dragonsurvival/textures/dragon/sea_dragon/adult.png` - 请这么写`\"dragonsurvival:textures/dragon/sea_dragon/adult.png\"`",
  "glow_skin": "皮肤发光纹理资源路径 此处的资源的注册方式与原版的`\"命名空间:资源路径\"`不同 - 若用图片`assets/dragonsurvival/textures/dragon/sea_dragon/adult_glow.png` - 请这么写`\"dragonsurvival:textures/dragon/sea_dragon/adult_glow.png\"`",
  "structure": "放置平台的结构id - 该项仅适用于`end_platforms.json - 末地平台`",
  "spawn_position": "放置平台的坐标 - 该项仅适用于`end_platforms.json - 末地平台`",
  "experience_cost": "与激活的信标交互时的经验消耗 (默认值：0)",
  "duration_multiplier": "效果持续时间乘数 (默认值：1)",
  "amplifier_modification": "效果等级乘数 (默认值：0)",
  "duration": "默认值：无限持续时间",
  "amplifier": "默认值：0",
  "attribute": "生物属性(https://zh.minecraft.wiki/w/属性)",
  "amount": "控制属性修改的数值和计算方式",
  "operation": "对数据的操作方式",
  "precise_base": "基础值",
  "precise_amount": "每级增量值",
  "type": "等级依赖函数(https://zh.minecraft.wiki/w/魔咒数据格式/等级依赖函数)",
  "activation": "决定能力如何激活",
  "upgrade": "定义能力的最大等级及升级方式 (如果未定义升级，最大等级将为1)",
  "usage_blocked": "如果条件匹配则禁用该能力 谓词(https://zh.minecraft.wiki/w/谓词)",
  "actions": "定义能力实际效果",
  "can_be_manually_disabled": "决定是否可以通过物种界面按CTRL+点击来禁用该能力 (默认: true)",
  "texture_entries": "根据等级决定将使用的贴图",
  "activation_type": "能力激活类型 - `dragonsurvival:passive` 被动激活(持续不断的触发) - `dragonsurvival:simple` 简单激活(施法成功后只触发一次) - `dragonsurvival:channeled` 引导激活(施法成功后按住持续触发)",
  "texture_resource": "该等级将使用的技能图标(必须放在'assets/<命名空间>/textures/gui/sprites'目录中) (需要省略'textures/gui/sprites'路径和'.png'文件扩展名)",
  "from_level": "指定从哪个等级开始使用对应的图标 (该条目定义了一个阶梯函数，每个`from_level`决定了对应区间的起点)",
  "continuous_mana_cost": "能力激活期间的法力消耗",
  "cooldown": "施法成功后的冷却时间",
  "trigger": "能力触发时机 (默认：dragonsurvival:constant)",
  "trigger_type": "激活触发器类型 - `dragonsurvival:constant` 恒定触发 - `dragonsurvival:on_self_hit` 当自己受到伤害时触发 - `dragonsurvival:on_target_hit` 当目标受到伤害时触发 - `dragonsurvival:on_target_killed` 当目标被击杀时触发 - `dragonsurvival:on_death` 当死亡时触发 - `dragonsurvival:on_block_break` 当破坏方块时 - `dragonsurvival:on_key_pressed` 当按键按下时 - `dragonsurvival:on_key_released` 当按键施放时",
  "condition": "可用于进行伤害上下文相关检查 可用参数： - this_entity(能力持有者) - origin - damage_source - attacking_entity(可选) - direct_attacking_entity(可选) 谓词(https://zh.minecraft.wiki/w/谓词)",
  "keys": "https://zh.minecraft.wiki/w/键控代码",
  "initial_mana_cost": "法力消耗(在施法时间完成时消耗)",
  "cast_time": "施放能力所需的蓄力时间",
  "notification": "指定在以下情况下显示的消息： - 没有足够的法力来启动施法 - 能力被阻止('usage_blocked'条件) (默认情况下，每个能力都会有一个包含\"法力不足\"消息的通知条目)",
  "can_move_while_casting": "施法者是否可以在施法时移动 (默认：true)",
  "sound": "在能力的各个阶段播放的音效 (简单激活不支持循环音效)",
  "animations": "在能力的各个阶段播放的动画 (简单激活不支持循环动画)",
  "max_duration": "技能持续释放的时间限制(单位：ticks) 并且，在达到该限制后会尝试执行带有`\"trigger_point\":\"channel_completion\"`的`actions`项",
  "not_enough_mana": "没有足够的法力来施法时的提示信息",
  "start": "施法开始时的音效",
  "charging": "蓄力开始时的音效",
  "end": "施法结束时的音效",
  "looping": "施法中的循环音效",
  "start_and_charging": "最开始蓄力的动画 (例如 吐息喷吐前的蓄力动画)",
  "starting_animation_key": "施法开始时的第一段动画 这里需要填入动画id",
  "looping_animation_key": "第一段动画结束后的循环动画 这里需要填入动画id",
  "layer": "动画层",
  "transition_length": "动画过渡时间 (默认：0)",
  "locks_neck": "锁定脖子",
  "locks_tail": "锁定尾巴",
  "animation_key": "施法开始时的循环动画 这里需要填入动画id",
  "upgrade_type": "升级所用的方式 - `dragonsurvival:experience_points` 通过消耗经验升级 - `dragonsurvival:experience_levels` 通过经验等级自动升级 - `dragonsurvival:dragon_growth` 通过成长度升级 - `dragonsurvival:item_based` 通过物品升级 - `dragonsurvival:condition_based` 通过条件判断升级",
  "maximum_level": "最大技能等级",
  "level_requirement": "解锁该等级所需的经验等级",
  "growth_requirement": "解锁该等级所需的龙成长值",
  "items_per_level": "每个等级的有效物品(用于解锁该等级)",
  "downgrade_items": "可用于降级的物品",
  "conditions": "解锁下一等级的条件 谓词(https://zh.minecraft.wiki/w/谓词)",
  "require_previous": "如果启用，只有在前置条件也匹配时才能解锁下一级升级 如果禁用，则最高匹配条件的等级决定当前等级",
  "target_selection": "定义如何选择目标以及效果的定义",
  "trigger_rate": "效果触发的频率(current_tick % rate == 0)",
  "trigger_point": "指定该效果触发的施法阶段 (自龙生`1.21.1-v2.0.36-26.09.2025`加入) - `default` 默认（施法成功后触发）",
  "target_type": "目标选择器 - `dragonsurvival:area` 以施法者为中心radius半径内的目标 - `dragonsurvival:dragon_breath` 施法者前方的锥形区域内的目标 - `dragonsurvival:looking_at` 施法者正在看向的特定实体或方块 - `dragonsurvival:self` 施法者自身 - `dragonsurvival:disc` 玩家周围的圆柱形区域",
  "applied_effects": "定义效果的执行类型以及效果",
  "range_multiplier": "默认范围基于施法者的体型比例",
  "range": "最大距离",
  "height": "用于实体选择的 圆柱体范围高度",
  "height_starts_below": "如果启用，圆盘的起始高度将下移1格(默认：false) (适用于以施法者所站地面为目标的情况)",
  "target_conditions": "决定选择哪些实体作为目标 - 可用的战利品上下文： - attacking_entity(施法者) - this_entity(目标) - origin(目标位置) 谓词(https://zh.minecraft.wiki/w/谓词)",
  "targeting_mode": "对要选择的实体进行预过滤 (具有施法者和目标之间的上下文，允许进行适当的盟友或敌人检查) - `all` 任何目标 - `allies` 只选中被视为盟友的实体 - `allies_and_self` 与'Allies'相同，但也包括施法者自身 - `non_allies` 选中任何非盟友 - `non_enemies` 排除被视为敌人的实体，可能包括：(分类为怪物的实体、以施法者为目标的生物) - `neutral` 选中中立实体(非盟友且非敌人) - `enemies` 选中被视为敌人的实体，可能包括：(分类为怪物的实体、以施法者为目标的生物) - `items` 选中物品 - `all_except_self` 选中除施法者之外的任何目标",
  "effect_type": "实体效果类型 - `dragonsurvival:damage` 造成伤害 - `dragonsurvival:modifier` 添加生物属性修改(https://zh.minecraft.wiki/w/属性) - `dragonsurvival:potion` 施加药水效果 - `dragonsurvival:projectile` 发射自定义弹射物 - `dragonsurvival:summon_entity` 召唤实体 - `dragonsurvival:damage_modification` 修改受到的伤害 - `dragonsurvival:breath_particles` 生成龙息粒子 - `dragonsurvival:ignite` 点燃实体 - `dragonsurvival:harvest_bonus` 调整挖掘速度 - `dragonsurvival:on_attack` 在攻击时触发 - `dragonsurvival:flight` 启用飞行能力 - `dragonsurvival:spin` 触发旋转攻击 - `dragonsurvival:item_conversion` 转换物品实体的物品类型 - `dragonsurvival:swim` 允许龙在特定流体中游泳，并配置最大氧气值 - `dragonsurvival:effect_modification` 修改状态效果的持续时间和等级 - `dragonsurvival:particle` 生成粒子 - `dragonsurvival:glow` 使实体发光 - `dragonsurvival:oxygen_bonus` 在特定流体中增加氧气值，允许龙在水下或熔岩中停留更长时间，支持无限氧气模式 - `dragonsurvival:block_vision` 让指定方块生成粒子进行标记 - `dragonsurvival:run_function` 运行函数 - `dragonsurvival:smelting` 熔炼物品 - `dragonsurvival:heal` 治疗实体 - `dragonsurvival:teleport` 传送实体 - `dragonsurvival:push` 推动实体 - `dragonsurvival:hunger` 调整饥饿值 - `dragonsurvival:effect_removal` 移除效果 - `dragonsurvival:use_item` 对目标实体使用特定物品 - `dragonsurvival:dragon_growth` 调整龙成长值 - `dragonsurvival:mana_recovery` 恢复魔法值 - `dragonsurvival:experience` 调整玩家经验值 - `dragonsurvival:cooldown_recovery` 能力/技能冷却时间恢复",
  "damage_type": "伤害类型(https://zh.minecraft.wiki/w/伤害类型定义格式)",
  "scale": "伤害缩放属性(https://zh.minecraft.wiki/w/属性) 将作为 `scale` 变量在 `expression` 表达式中使用 - 默认为 `dragonsurvival:dragon_ability_damage`",
  "expression": "使用 EvalEx 表达式引擎计算最终伤害值的数学公式 (https://ezylang.github.io/EvalEx/references/references.html) - 默认值: `\"amount * scale\"`",
  "use_claw": "是否在造成伤害时临时装备龙爪上的工具 (默认: false)",
  "modifiers": "定义将要应用的生物属性修改(https://zh.minecraft.wiki/w/属性)",
  "potion": "定义将要使用的药水效果",
  "probability": "控制效果触发的概率 0 (0%) 到 1 (100%) (默认：1)",
  "effect_particles": "是否显示效果粒子 (默认：false)",
  "show_icon": "是否在HUD显示效果图标 (默认：true)",
  "projectile_data": "该技能所自定义的弹射物数据 - 可引用自 `data/dragonsurvival/projectile_data` 在外部编写，例如 `\"dragonsurvival:ball_lightning\"` - 或者直接在此填写(但是不建议，由于数据过多影响可读性，该mcdoc也未在此实现)",
  "target_direction": "发射方向",
  "number_of_projectiles": "单次发射的弹射物数量",
  "projectile_spread": "弹道扩散",
  "speed": "弹射物初速度",
  "direction": "朝向 - `looking_at` 视线方向 - `towards_entity` 朝向实体方向 - `up` 上 - `down` 下 - `east` 东 - `west` 西 - `south` 南 - `north` 北",
  "entities": "加权列表允许自定义权重 否则每个实体将具有相同的权重(因此相同几率)",
  "max_summons": "每个实例最多召唤的实体数量",
  "attribute_scales": "调整召唤实体的属性(https://zh.minecraft.wiki/w/属性)",
  "nbt": "调整召唤实体的nbt",
  "is_allied": "如果启用，实体将被召唤者拥有并被视为盟友(默认：true) (这也意味着可以通过相关按键绑定改变攻击和移动行为)",
  "data": "实体id",
  "weight": "权重值",
  "attributes": "生物属性(https://zh.minecraft.wiki/w/属性)",
  "damage_types": "将调整的伤害类型(https://zh.minecraft.wiki/w/伤害类型定义格式)",
  "multiplier": "值'0'表示目标将对此伤害免疫",
  "spread": "控制粒子发射的扩散角度或范围",
  "speed_per_growth": "根据成长值计算粒子的速度 speed_per_growth * 成长值",
  "main_particle": "主要粒子",
  "secondary_particle": "次级粒子",
  "ignite_ticks": "点燃时间(ticks)",
  "blocks": "决定这项加成适用的方块 同时决定效果悬停提示信息，例如： - 若此项填入 `#minecraft:mineable/axe`     则显示 \"工具类型: 斧\" - 若此项填入 `#minecraft:mineable/hoe`     则显示 \"工具类型: 锄\" - 若此项填入 `#minecraft:mineable/shovel`  则显示 \"工具类型: 铲\" - 若此项填入 `#minecraft:mineable/pickaxe` 则显示 \"工具类型: 镐\" - 若不是上述项则显示为空",
  "base_speed": "基础挖掘速度 - 该项不会影响挖掘等级!!! - 由其中指定的工具类型决定`基础挖掘速度`",
  "harvest_bonus": "基础挖掘等级(决定方块被挖掘后是否掉落物品) - 该项不会影响挖掘速度!!! - 由结果决定挖掘等级，例如   - 1 = 木制/金制   - 2 = 石制   - 3 = 铁制   - 4 = 钻石制/下界合金制",
  "break_speed_multiplier": "附加挖掘速度 - 计算方式: 1 + break_speed_multiplier",
  "tiers": "将使用的工具类型",
  "tier": "工具类型",
  "fluid_types": "旋转效果可以使用的流体 (如果未指定，则只能在空中使用)",
  "item_conversions": "一个转换的列表",
  "item_predicate": "决定哪些物品将被转换",
  "items_to": "要转换成的物品的加权列表",
  "item": "需要转化成的物品id",
  "conversion_rate": "转换量",
  "particles": "粒子",
  "max_oxygen": "实体在指定流体中可以憋气的时间(以刻为单位) (值'-1'表示无限氧气)",
  "fluid_type": "实体可以游泳的流体类型",
  "modifications": "定义要修改的效果",
  "duration_modification": "持续时间修改",
  "particle_data": "粒子数据",
  "particle_count": "粒子数量",
  "color": "发光颜色",
  "oxygen_bonus": "控制提供的氧气加成量",
  "display_type": "决定如何标记方块 - `outline` 勾勒方块轮廓，可以透过其他方块看到 - `particles` 在方块周围创建粒子 - `simple_shader` 在方块表面简单的覆盖一层着色",
  "colors": "要使用的颜色 - 如果指定了多个，将在它们之间循环",
  "particle_rate": "粒子速率 默认: 10",
  "color_shift_rate": "颜色变化速率 默认: 1",
  "alpha": "默认: 0.3",
  "function": "Minecraft函数",
  "progress": "每次效果应用时增加的熔炼进度(1 = 100%) 如果物品在3秒内不再被熔炼，进度将重置 (如果未指定进度，物品将立即熔炼完成)",
  "grants_experience": "是否授予熔炼经验(在配方中定义) (默认：true)",
  "percentage": "目标实体最大生命值的百分比(1 = 100%)将被治疗",
  "push_force": "控制施加推力的大小(可为负数)",
  "hunger_gain": "饥饿值增益(可用负值表示消耗) 直接增加或减少玩家的饥饿值(食物条)",
  "saturation_gain": "饱和度增益 直接增加玩家的饱和度(隐藏的饱食度)",
  "maximum_saturation": "最大饱和度 设置通过此能力获得的饱和度上限",
  "categories": "按效果类别过滤要移除的状态效果 - BENEFICIAL(有益) - HARMFUL(有害) - NEUTRAL(中性)",
  "valid_effects": "指定要移除状态效果列表",
  "max_amount": "限制单次最多移除多少个状态效果",
  "maximum_effect_level": "只移除低于或等于指定等级的效果",
  "valid_entities": "过滤哪些实体可以成为目标",
  "growth_type": "决定如何应用成长值 - add(相加) - set(设置)",
  "action_type": "值的指定方式 - Flat: 按amount取值 - Percent: 根据当前百阶段进行缩放   - 公式: amount * (max_growth - min_growth) (max_growth与min_growth均取自当前阶段)",
  "adjustment_type": "决定数值的计算方式 - percent(百分比) - flat(数值)",
  "experience_type": "经验处理类型 - `levels` 按等级计算 - `points` 按经验点数计算",
  "abilities": "可选的能力/技能集合",
  "exclude_this": "是否排除自身能力 (默认: true)",
  "id": "要创建的实例的唯一ID 可在实体子谓词 `dragonsurvival:custom_predicates` 中用于检测",
  "should_remove_automatically": "如果启用，创建的实例将在以下情况下被移除(默认：false)： - 施法者的能力不再激活(适用于所有实例) - 能力的目标条件不再匹配(仅适用于施法者的实例)",
  "early_removal_condition": "导致实例在匹配时被移除的条件 谓词(https://zh.minecraft.wiki/w/谓词)",
  "custom_icon": "如果未提供自定义图标，将使用能力/缺陷图标代替 此处的资源的注册方式与原版的`\"命名空间:资源路径\"`不同 - 若用图片`assets/dragonsurvival/textures/ability_effect/fire_immunity.png` - 请这么写`\"dragonsurvival:textures/ability_effect/fire_immunity.png\"`",
  "is_hidden": "如果启用，实例将不会显示为效果 (默认：false)",
  "attempts": "骨粉应用的频率",
  "conversion_data": "转化速率",
  "from_predicate": "决定哪些方块将被转换",
  "blocks_to": "要转换成的方块的加权列表",
  "state": "指定方块数据",
  "ignite_probability": "点燃概率",
  "delay": "药水云生效前的延迟时间",
  "particle": "粒子效果",
  "valid_blocks": "决定哪些方块将被破坏",
  "drop_loot": "破坏方块时掉落战利品(如果有的话) (默认：false)",
  "power": "爆炸强度",
  "fire": "能产生火焰 (默认: true)",
  "tool": "指定所用的工具",
  "unlock_condition": "解锁条件 谓词(https://zh.minecraft.wiki/w/谓词)",
  "visibility": "可见性 - always_visible    始终可见 - always_hidden     始终隐藏 - visible_if_locked 如果锁定则可见",
  "is_default": "决定此身体是否是默认身体全局列表的一部分(默认：false)",
  "unlockable_behavior": "指定此身体的解锁条件及其在龙编辑器中的可见性",
  "can_hide_wings": "决定翅膀是否可以隐藏 (默认：true)",
  "texture_size": "贴图大小(默认512x512)",
  "animation": "此身体使用的动画文件 (位于`assets/<命名空间>/animations/`下的`.json`文件)",
  "default_icon": "默认GUI图标，在当前物种没有特定图标时使用",
  "bones_to_hide_for_toggle": "当翅膀隐藏时将隐藏的骨骼列表 (默认：'WingLeft', 'WingRight', 'SmallWingLeft' 和 'SmallWingRight')",
  "emotes": "此身体可以使用的表情 - 可引用自 `data/dragonsurvival/dragon_emote_set/`中的`json`文件在外部编写，例如 `\"dragonsurvival:default_emotes\"` - 或者直接在此填写(但是不建议，可能影响可读性)",
  "scaling_proportions": "高度和宽度尺寸如何计算(使用实体的当前比例)",
  "crouch_height_ratio": "决定下蹲时高度变化多少",
  "mounting_offset": "决定骑乘者的放置位置",
  "backpack_offset": "决定背包的放置位置(基础位置是骨骼'BackpackBone')",
  "bettercombat_weapon_offset": "与 Better Combat 模组兼容的武器位置偏移",
  "translation_override": "翻译覆盖 - 如果不提供，使用`animationKey`作为翻译键",
  "loops": "动画是否循环播放 (默认:fasle)",
  "blend": "动画是否允许与其他动画混合 (默认:fasle)",
  "locks_head": "该动画是否锁定头部 (默认:fasle)",
  "third_person": "是否主要在第三人称下显示 (默认:fasle)",
  "can_move": "是否允许玩家在动画中移动 (默认:fasle)",
  "sound_event": "音效id",
  "volume": "音效音量 (默认：1)",
  "pitch": "音效音调 (默认：1)",
  "interval": "决定音效播放的频率(计算方式为 emote_ticks % interval == 0)",
  "width": "龙的身体宽度",
  "eye_height": "眼睛高度(视角高度)",
  "scale_multiplier": "整体缩放倍率 (默认：1)",
  "shadow_multiplier": "阴影大小倍率 (默认：1)",
  "human_offset": "人类骑乘位置偏移 (默认：[0, 0, 0])",
  "dragon_offset": "龙类骑乘位置偏移 (默认：[0, 0, 0])",
  "offset_per_scale_above_one": "缩放相关的额外偏移 (默认：[0, 0, 0])",
  "position_offset": "位置偏移 (默认：[0, 0, 0])",
  "rotation_offset": "旋转偏移 (默认：[0, 0, 0])",
  "effect": "定义缺陷的效果",
  "penalty_type": "缺陷效果类型 - `dragonsurvival:take_damage` 造成伤害 - `dragonsurvival:mob_effect` 给予药水效果 - `dragonsurvival:item_blacklist` 物品黑名单 - `dragonsurvival:damage_modification` 修改收到的伤害参数 - `dragonsurvival:fear` 让生物恐惧玩家 - `dragonsurvival:informational` 信息(无实际效果，仅供测试) - `dragonsurvival:modifier` 添加生物属性修改(https://zh.minecraft.wiki/w/属性) - `dragonsurvival:effect_modification` 修改状态效果的持续时间和等级 - `dragonsurvival:run_function` 运行函数",
  "entity_condition": "决定哪些实体受影响 - 可用的战利品上下文： - this_entity(目标) - origin(目标位置) 谓词(https://zh.minecraft.wiki/w/谓词)",
  "distance": "决定在实体逃跑前您可以接近它的距离 最大允许距离为64",
  "walk_speed": "实体逃跑时的行走移动速度修正值(默认：1)",
  "sprint_speed": "实体逃跑时的冲刺移动速度修正值(默认：1.3) 当您太接近实体时使用此值",
  "penalty_trigger": "缺陷触发器类型 - `dragonsurvival:supply` 定义缺陷条触发 - `dragonsurvival:instant` 即时触发 - `dragonsurvival:item_used` 物品使用触发 - `dragonsurvival:hit_by_projectile` 被投射物击中触发 - `dragonsurvival:hit_by_water_potion` 被药水击中触发",
  "supply_type": "缺陷条将使用的图标 图标路径：`assets\\dragonsurvival\\textures\\gui\\custom\\supply_icons\\<supply_type>.png` 图标规格：9x9像素单图标，横向拼接为27x9像素的PNG图片",
  "reduction_rate": "当触发条件满足时，缺陷条减少的比例(使用百分比)",
  "regeneration_rate": "当触发条件不再满足时，缺陷条恢复的比例(使用百分比)",
  "recovery_items": "可用于缓解或消除缺陷的特殊物品列表",
  "display_like_hunger_bar": "是否在UI界面中以类似饥饿条的形式显示此缺陷状态 (默认:false)",
  "particles_on_trigger": "当惩罚效果触发时使用的粒子效果",
  "item_predicates": "能够缓解此缺陷的物品列表(使用物品谓词)",
  "percent_restored": "使用该物品后缺陷条的恢复比例(使用百分比)",
  "starting_growth": "初始成长值将为此值或第一阶段的最小成长值",
  "mana_handling": "指定一些法力交互 特别是经验值(等级)如何与之交互(例如，当所有法力耗尽时，将经验值转换为法力)",
  "custom_stage_progression": "如果不使用全局默认的阶段列表，可以定义此项 标签将使用 `data/命名空间/tags/dragonsurvival/dragon_stage/` 中指定json文件包含的数据",
  "bodies": "如果不使用全局默认的身体类型列表，可以定义此项 标签将使用 `data/命名空间/tags/dragonsurvival/dragon_body/` 中指定json文件包含的数据",
  "penalties": "指定此物种拥有的缺陷 标签将使用 `data/命名空间/tags/dragonsurvival/dragon_penalty/` 中指定json文件包含的数据",
  "misc_resources": "指向物种相关各种资源(纹理等)的位置",
  "mana_xp_conversion": "指定经验值转换为法力的比率(默认：0) 如果值为0，则不进行转换 (默认的'mana_handling'条目使用值0.1，表示1点法力=10点经验值)",
  "mana_per_level": "指定每经验等级获得多少法力(默认：0) 如果值为0，则不授予额外法力 (默认的'mana_handling'条目使用值0.25，表示每4个经验等级=1点法力)",
  "max_mana_from_levels": "指定通过经验等级可以获得的最大法力值(默认：0) 如果值为0，则不授予额外法力 (默认的'mana_handling'条目使用值9，表示在经验等级36时达到上限)",
  "food_sprites": "食物条图标 - 如果未指定，将渲染原版食物条 此处的资源的注册方式与原版的`\"命名空间:资源路径\"`不同 - 若用图片`assets/dragonsurvival/textures/gui/custom/food_icons/sea_food_icons.png` - 请这么写`\"dragonsurvival:textures/gui/custom/food_icons/sea_food_icons.png\"`",
  "mana_sprites": "法力图标 - 如果未指定，将使用通用纹理 (以物种的主色调着色)",
  "altar_banner": "在龙祭坛和物种界面中使用的横幅 此处的资源的注册方式与原版的`\"命名空间:资源路径\"`不同 - 若用图片`assets/dragonsurvival/textures/gui/custom/altar/sea/altar_icon.png` - 请这么写`\"dragonsurvival:textures/gui/custom/altar/sea/altar_icon.png\"`",
  "ability_bar": "施法条 此处的资源的注册方式与原版的`\"命名空间:资源路径\"`不同 - 若用图片`assets/dragonsurvival/textures/gui/custom/casting_bars/sea/cast_bar.png` - 请这么写`\"dragonsurvival:textures/gui/custom/casting_bars/sea/cast_bar.png\"`",
  "growth_left_arrow": "左箭头，用于在存在超过4个阶段时导航 (如果未指定，将使用通用图标)",
  "growth_right_arrow": "右箭头，用于在存在超过4个阶段时导航 (如果未指定，将使用通用图标)",
  "growth_crystal": "成长水晶 - 根据阶段内的进度填充",
  "food_tooltip": "确定饮食条目的工具提示渲染方式",
  "primary_color": "龙饮食工具提示文本和边框颜色 通用法力图标颜色",
  "secondary_color": "龙饮食工具提示边框颜色",
  "claw_texture_slot": "确定使用哪个爪物品(等级)来渲染爪纹理 - sword    剑 - pickaxe  镐 - shovel   锹 - axe      斧",
  "full": "满法力点 此处的资源的注册方式与原版的`\"命名空间:资源路径\"`不同 - 若用图片`assets/dragonsurvival/textures/gui/custom/mana_icons/sea/full.png` - 请这么写`\"dragonsurvival:textures/gui/custom/mana_icons/sea/full.png\"`",
  "reserved": "保留的法力点 此处的资源的注册方式与原版的`\"命名空间:资源路径\"`不同 - 若用图片`assets/dragonsurvival/textures/gui/custom/mana_icons/sea/reserved.png` - 请这么写`\"dragonsurvival:textures/gui/custom/mana_icons/sea/reserved.png\"`",
  "recovery": "当恢复法力时，在'recovery'和'empty'之间切换 此处的资源的注册方式与原版的`\"命名空间:资源路径\"`不同 - 若用图片`assets/dragonsurvival/textures/gui/custom/mana_icons/sea/recovery.png` - 请这么写`\"dragonsurvival:textures/gui/custom/mana_icons/sea/recovery.png\"`",
  "empty": "施法时 此处的资源的注册方式与原版的`\"命名空间:资源路径\"`不同 - 若用图片`assets/dragonsurvival/textures/gui/custom/mana_icons/sea/empty.png` - 请这么写`\"dragonsurvival:textures/gui/custom/mana_icons/sea/empty.png\"`",
  "font": "使用的自定义字体(https://zh.minecraft.wiki/w/自定义字体) (默认：dragonsurvival:food_tooltip_icon_font)",
  "nutrition_icon": "营养图标 码位字符串(https://zh.minecraft.wiki/w/自定义字体#码位字符串)",
  "saturation_icon": "饱和度图标 码位字符串(https://zh.minecraft.wiki/w/自定义字体#码位字符串)",
  "growth_range": "阶段的最小和最大成长值",
  "ticks_until_grown": "达到最大成长所需的刻数(可以在1刻到1年之间指定)(20刻 = 1秒)",
  "growth_items": "可用于增加(或减少)龙成长值的物品",
  "is_natural_growth_stopped": "决定何时停止龙自然成长的条件",
  "destruction_data": "破坏行为数据",
  "growth_in_ticks": "每次使用增加的成长值 值为0会使物品改为切换'is_growth_stopped'字段 (该字段在默认的'is_natural_growth_stopped'条件中使用)",
  "maximum_usages": "决定此物品可以使用多少次(默认：无限)",
  "crushing_growth": "龙行走时能对实体造成碾压伤害的最小成长值",
  "block_destruction_growth": "龙行走时能破坏方块的最小成长值",
  "crushing_damage_scalar": "决定碾压伤害如何缩放(成长值 * 比例因子)",
  "block_predicate": "决定龙行走时能够破坏的方块",
  "entity_predicate": "决定行走时碾压伤害作用的实体",
  "general_data": "决定自定义弹射物的效果 - 执行顺序:   1. ticking_effects   2. entity_hit_effects / block_hit_effects   4. common_hit_effects",
  "type_data": "决定自定义弹射物的外观 - 若是`texture`+`piercing_level`则是自定义箭类实体 - 若是`resources`+`behaviour_data`则是自定义火球类实体",
  "name": "注册的自定义弹射物名称",
  "is_impact_projectile": "决定该实体能不能破坏击中的 陶罐、紫颂花 等方块 (默认: false)",
  "block_hit_effects": "击中方块时执行的效果 - 执行者: `server` - 执行位置: 击中方块的方块中心",
  "common_hit_effects": "击中任何东西都会执行的效果 - `world_effect`   - `dragonsurvival:point`      - `执行者`: 弹射物自身      - `执行位置`: 弹射物击中判定成功时的位置(会出现在弹射物的轨迹上)   - `dragonsurvival:area`      - `执行者`: 弹射物自身      - `执行位置`: 范围内所有复合的实体(不包括弹射物本身) - `entity_effect`   - `dragonsurvival:point`     - 无任何效果   - `dragonsurvival:area`     - `执行者`: 范围内所有符合的实体(不包括弹射物本身)     - `执行位置`: 弹射物击中判定成功时的位置(会出现在弹射物的轨迹上) - `block_effect`   - `dragonsurvival:point`     - `执行者`: `server`     - `执行位置`: 弹射物击中判定成功时的 `方块位置中心`(会出现在弹射物的轨迹上)   - `dragonsurvival:area`     - `执行者`: `server`     - `执行位置`: 弹射物为中心范围内所有符合的方块中心",
  "entity_hit_condition": "击中实体的谓词判断(用于`entity_hit_effects`) 具有施法者和目标之间的上下文，允许进行适当的盟友或敌人检查 谓词(https://zh.minecraft.wiki/w/谓词)",
  "entity_hit_effects": "击中实体时执行的效果 - 执行者：被击中的实体 - 执行位置：被击中的实体",
  "ticking_effects": "弹射物未落地时，每tick都会执行的效果 - `world_effect`   - `dragonsurvival:point`      - `执行者`: 弹射物自身      - `执行位置`: 弹射物击中判定成功时的位置(会出现在弹射物的轨迹上)   - `dragonsurvival:area`      - `执行者`: 弹射物自身      - `执行位置`: 范围内所有复合的实体(不包括弹射物本身) - `entity_effect`   - `dragonsurvival:point`     - 无任何效果   - `dragonsurvival:area`     - `执行者`: 范围内所有符合的实体(不包括弹射物本身)     - `执行位置`: 弹射物击中判定成功时的位置(会出现在弹射物的轨迹上) - `block_effect`   - `dragonsurvival:point`     - `执行者`: `server`     - `执行位置`: 弹射物击中判定成功时的 `方块位置中心`(会出现在弹射物的轨迹上)   - `dragonsurvival:area`     - `执行者`: `server`     - `执行位置`: 弹射物为中心范围内所有符合的方块中心",
  "particle_trail": "粒子效果",
  "tick_rate": "效果触发的频率(current_tick % rate == 0) (默认: 0)",
  "chance": "效果触发的概率 (默认：1)",
  "world_effect": "世界效果 可用效果列表: - `dragonsurvival:explosion` 造成爆炸 - `dragonsurvival:lightning` 召唤闪电 - `dragonsurvival:particle` 生成粒子 - `dragonsurvival:run_function` 运行函数",
  "explosion_power": "爆炸强度",
  "break_blocks": "能破坏方块",
  "can_damage_self": "能伤害自己",
  "block_effect": "方块效果 - `dragonsurvival:particle` 生成粒子 - `dragonsurvival:run_function` 运行函数 - `dragonsurvival:area_cloud` 生成药水云",
  "entity_effect": "实体效果 - `dragonsurvival:damage` 造成伤害 - `dragonsurvival:potion` 施加药水效果 - `dragonsurvival:lightning` 生成闪电 - `dragonsurvival:particle` 生成粒子 - `dragonsurvival:run_function` 运行函数 - `dragonsurvival:push` 推动实体",
  "can_hurt_self": "能伤害自己",
  "spawns_fire": "产生火焰",
  "ignores_items_and_experience": "忽略物品与经验球",
  "piercing_level": "箭类实体能射穿实体的数量 此值将会复制到同名nbt中",
  "resources": "贴图数据 空/无效 数据可能导致游戏崩溃",
  "behaviour_data": "基本数据",
  "on_destroy_effects": "当实体消失时将会执行的效果 - `world_effect`   - `dragonsurvival:point`      - `执行者`: 弹射物自身      - `执行位置`: 弹射物击中判定成功时的位置(会出现在弹射物的轨迹上)   - `dragonsurvival:area`      - `执行者`: 弹射物自身      - `执行位置`: 范围内所有复合的实体(不包括弹射物本身) - `entity_effect`   - `dragonsurvival:point`     - 无任何效果   - `dragonsurvival:area`     - `执行者`: 范围内所有符合的实体(不包括弹射物本身)     - `执行位置`: 弹射物击中判定成功时的位置(会出现在弹射物的轨迹上) - `block_effect`   - `dragonsurvival:point`     - `执行者`: `server`     - `执行位置`: 弹射物击中判定成功时的 `方块位置中心`(会出现在弹射物的轨迹上)   - `dragonsurvival:area`     - `执行者`: `server`     - `执行位置`: 弹射物为中心范围内所有符合的方块中心",
  "trail_particle": "拖尾粒子",
  "max_bounces": "最大弹跳的次数(撞到方块或实体后反弹，若达到最大限制则尝试滞留)",
  "max_lingering_ticks": "最大滞留时间(碰撞后停止移动的时间，若达到最大限制则尝试移除实体) (单位：ticks)",
  "max_movement_distance": "最大移动距离(若达到最大限制则尝试移除实体)",
  "max_lifespan": "最大存在时间(若达到最大限制则尝试移除实体) (单位：ticks)",
  "swirls": "是否启用漩涡效果",
  "projectile_level": "弹射物等级 (复制自召唤该实体的技能等级)",
  "bounces": "已弹跳的次数(撞到方块或实体后反弹，若达到最大限制则尝试`滞留`)",
  "lingering_ticks": "已滞留的时间(碰撞后停止移动的时间，若达到最大限制则尝试移除实体) (单位：ticks)",
  "movement_distance": "已移动的距离(若达到最大限制则尝试移除实体)",
  "lifespan": "已存在的时间(若达到最大限制则尝试移除实体) (单位：ticks)",
};